// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPwZSivyxzGUNHjnhPjpT7syeW8tTMrYA',
    appId: '1:909668627382:web:a2077fe4febfdf311d0717',
    messagingSenderId: '909668627382',
    projectId: 'meteo-f6152',
    authDomain: 'meteo-f6152.firebaseapp.com',
    databaseURL: 'https://meteo-f6152-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'meteo-f6152.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9xFnK4q74iLeNyM_A8joZ72Q_wnRj8c8',
    appId: '1:909668627382:android:2e0f7c0877711f951d0717',
    messagingSenderId: '909668627382',
    projectId: 'meteo-f6152',
    databaseURL: 'https://meteo-f6152-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'meteo-f6152.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr7VwlGboRjlUURj35EDloFF5dRXO3jKU',
    appId: '1:909668627382:ios:f78cb2e9c703f9e51d0717',
    messagingSenderId: '909668627382',
    projectId: 'meteo-f6152',
    databaseURL: 'https://meteo-f6152-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'meteo-f6152.firebasestorage.app',
    iosBundleId: 'com.example.maStation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr7VwlGboRjlUURj35EDloFF5dRXO3jKU',
    appId: '1:909668627382:ios:f78cb2e9c703f9e51d0717',
    messagingSenderId: '909668627382',
    projectId: 'meteo-f6152',
    databaseURL: 'https://meteo-f6152-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'meteo-f6152.firebasestorage.app',
    iosBundleId: 'com.example.maStation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPwZSivyxzGUNHjnhPjpT7syeW8tTMrYA',
    appId: '1:909668627382:web:f999d62575fac2b11d0717',
    messagingSenderId: '909668627382',
    projectId: 'meteo-f6152',
    authDomain: 'meteo-f6152.firebaseapp.com',
    databaseURL: 'https://meteo-f6152-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'meteo-f6152.firebasestorage.app',
  );
}
